spring.application.name=one23
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.vczuscrkquqmgezselov
spring.datasource.password=shreyu240810

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true